title: Test GithubPage Blog
author: SChen00
email: hugochen1024@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: hugochen1024
github_username:  Schen1024

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
